-- BANQO Perú · esquema Supabase v1
-- Ejecutar completo en Supabase > SQL Editor.

create extension if not exists pgcrypto;

-- ---------- helpers ----------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------- perfiles ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'student' check (role in ('student','admin')),
  plan text not null default 'free' check (plan in ('free','pro','admin')),
  target_exam text default 'RESIDENTADO' check (target_exam in ('RESIDENTADO','ENAM','ESSALUD','TODOS')),
  stage text,
  xp integer not null default 0,
  streak integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists(
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$;

-- ---------- preguntas ----------
create table if not exists public.questions (
  id uuid primary key default gen_random_uuid(),
  external_id text not null unique,
  bank_type text not null default 'BANCO' check (bank_type in ('BANCO','SIMULACRO','PREGUNTA_SUELTA')),
  exam_type text not null default 'RESIDENTADO' check (exam_type in ('RESIDENTADO','ENAM','ESSALUD','OTRO')),
  bank_name text not null default 'BANQO',
  year integer,
  specialty text not null default 'Sin clasificar',
  topic text not null default 'Sin clasificar',
  subtopic text not null default 'Sin clasificar',
  section text not null default '',
  stem text not null,
  options jsonb not null default '{}'::jsonb,
  correct_answer text check (correct_answer is null or correct_answer in ('A','B','C','D','E')),
  explanation text not null default '',
  galactic_tip text not null default '',
  source_reference text not null default '',
  source_page integer,
  requires_image boolean not null default false,
  image_url text,
  status text not null default 'PENDIENTE' check (status in ('PENDIENTE','APROBADA','PUBLICADA','ARCHIVADA')),
  review_notes text not null default '',
  source_uid text,
  source_hash text,
  version integer not null default 1,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint questions_options_object check (jsonb_typeof(options) = 'object')
);

create index if not exists idx_questions_status on public.questions(status);
create index if not exists idx_questions_exam on public.questions(exam_type);
create index if not exists idx_questions_bank on public.questions(bank_name);
create index if not exists idx_questions_taxonomy on public.questions(specialty, topic, subtopic);
create index if not exists idx_questions_source_uid on public.questions(source_uid);

-- Historial editorial: conserva la versión previa cuando una importación modifica una pregunta.
create table if not exists public.question_versions (
  id bigint generated by default as identity primary key,
  question_id uuid not null references public.questions(id) on delete cascade,
  version integer not null,
  snapshot jsonb not null,
  changed_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique(question_id, version)
);

create index if not exists idx_question_versions_question on public.question_versions(question_id, version desc);

create trigger questions_set_updated_at
before update on public.questions
for each row execute procedure public.set_updated_at();

-- ---------- simulacros ----------
create table if not exists public.simulation_sets (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  exam_type text not null default 'RESIDENTADO' check (exam_type in ('RESIDENTADO','ENAM','ESSALUD','OTRO')),
  year integer,
  description text not null default '',
  duration_minutes integer,
  question_count integer not null default 0,
  status text not null default 'BORRADOR' check (status in ('BORRADOR','PUBLICADO','ARCHIVADO')),
  source_reference text not null default '',
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger simulation_sets_set_updated_at
before update on public.simulation_sets
for each row execute procedure public.set_updated_at();

create table if not exists public.simulation_questions (
  simulation_id uuid not null references public.simulation_sets(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  order_no integer not null,
  is_reserve boolean not null default false,
  primary key (simulation_id, question_id),
  unique (simulation_id, order_no)
);

-- ---------- importaciones admin ----------
create table if not exists public.import_batches (
  id uuid primary key default gen_random_uuid(),
  import_type text not null check (import_type in ('XLSX','CSV','JSON','PDF_RESALTADO')),
  bank_type text not null default 'BANCO' check (bank_type in ('BANCO','SIMULACRO','PREGUNTA_SUELTA')),
  exam_type text not null default 'RESIDENTADO' check (exam_type in ('RESIDENTADO','ENAM','ESSALUD','OTRO')),
  name text not null,
  file_name text,
  storage_path text,
  status text not null default 'PREVISUALIZADO' check (status in ('PREVISUALIZADO','IMPORTANDO','COMPLETADO','CON_ERRORES','CANCELADO')),
  total_rows integer not null default 0,
  valid_rows integer not null default 0,
  error_rows integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  report jsonb not null default '{}'::jsonb,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger import_batches_set_updated_at
before update on public.import_batches
for each row execute procedure public.set_updated_at();

create table if not exists public.import_items (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.import_batches(id) on delete cascade,
  row_number integer,
  external_id text,
  raw_data jsonb not null default '{}'::jsonb,
  normalized_data jsonb not null default '{}'::jsonb,
  status text not null default 'PENDIENTE' check (status in ('PENDIENTE','VALIDO','ERROR','IMPORTADO','OMITIDO')),
  errors jsonb not null default '[]'::jsonb,
  linked_question_id uuid references public.questions(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_import_items_batch on public.import_items(batch_id);

-- ---------- sesiones y respuestas ----------
create table if not exists public.study_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  session_type text not null check (session_type in ('PRACTICE','SIMULATION','DIAGNOSTIC')),
  simulation_id uuid references public.simulation_sets(id),
  filters jsonb not null default '{}'::jsonb,
  question_ids uuid[] not null default '{}'::uuid[],
  status text not null default 'EN_CURSO' check (status in ('EN_CURSO','COMPLETADA','ABANDONADA')),
  correct_count integer not null default 0,
  incorrect_count integer not null default 0,
  blank_count integer not null default 0,
  score numeric(6,2),
  elapsed_seconds integer not null default 0,
  xp_awarded boolean not null default false,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists idx_sessions_user on public.study_sessions(user_id, started_at desc);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.study_sessions(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  selected_answer text check (selected_answer is null or selected_answer in ('A','B','C','D','E')),
  is_correct boolean,
  marked boolean not null default false,
  discarded_options text[] not null default '{}'::text[],
  response_ms integer,
  answered_at timestamptz not null default now(),
  unique(session_id, question_id)
);

create index if not exists idx_attempts_user on public.attempts(user_id, answered_at desc);
create index if not exists idx_attempts_question on public.attempts(question_id);

create table if not exists public.favorites (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id, question_id)
);

create table if not exists public.user_notes (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  note text not null default '',
  updated_at timestamptz not null default now(),
  primary key(user_id, question_id)
);

create trigger user_notes_set_updated_at
before update on public.user_notes
for each row execute procedure public.set_updated_at();

create table if not exists public.question_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  reason text not null,
  comment text not null default '',
  status text not null default 'PENDIENTE' check (status in ('PENDIENTE','REVISADO','RESUELTO','DESCARTADO')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger question_reports_set_updated_at
before update on public.question_reports
for each row execute procedure public.set_updated_at();

-- ---------- dispositivo (base para 1 dispositivo por cuenta) ----------
create table if not exists public.device_sessions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  device_id text not null,
  device_name text,
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger device_sessions_set_updated_at
before update on public.device_sessions
for each row execute procedure public.set_updated_at();

-- ---------- límites del plan gratuito (servidor) ----------
create or replace function public.free_questions_remaining()
returns integer
language plpgsql
stable
security definer set search_path = public
as $$
declare
  uid uuid := auth.uid();
  p public.profiles%rowtype;
  used_n integer;
begin
  if uid is null then raise exception 'No autenticado'; end if;
  select * into p from public.profiles where id = uid;
  if p.role = 'admin' or p.plan in ('pro','admin') then return -1; end if;
  select count(*)::integer into used_n
  from public.attempts
  where user_id = uid
    and (answered_at at time zone 'America/Lima')::date = (now() at time zone 'America/Lima')::date;
  return greatest(0, 15 - used_n);
end;
$$;

create or replace function public.can_answer_today()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select public.free_questions_remaining() <> 0;
$$;

grant execute on function public.free_questions_remaining() to authenticated;
grant execute on function public.can_answer_today() to authenticated;

-- El cliente nunca debe poder resetear xp_awarded para cobrar XP dos veces.
create or replace function public.protect_study_session_internal()
returns trigger
language plpgsql
as $$
begin
  if current_user = 'authenticated' then
    new.xp_awarded := old.xp_awarded;
  end if;
  return new;
end;
$$;

drop trigger if exists protect_study_session_internal_fields on public.study_sessions;
create trigger protect_study_session_internal_fields
before update on public.study_sessions
for each row execute procedure public.protect_study_session_internal();

-- ---------- RLS ----------
alter table public.profiles enable row level security;
alter table public.questions enable row level security;
alter table public.question_versions enable row level security;
alter table public.simulation_sets enable row level security;
alter table public.simulation_questions enable row level security;
alter table public.import_batches enable row level security;
alter table public.import_items enable row level security;
alter table public.study_sessions enable row level security;
alter table public.attempts enable row level security;
alter table public.favorites enable row level security;
alter table public.user_notes enable row level security;
alter table public.question_reports enable row level security;
alter table public.device_sessions enable row level security;

-- perfiles
-- El alumno puede leer su propio perfil, pero NO puede elevar su rol/plan desde el navegador.
create policy "profiles_select_own_or_admin" on public.profiles
for select to authenticated using (id = auth.uid() or public.is_admin());
create policy "profiles_insert_self_student" on public.profiles
for insert to authenticated
with check (id = auth.uid() and role = 'student' and plan = 'free');
create policy "profiles_admin_update" on public.profiles
for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- preguntas
create policy "questions_read_published" on public.questions
for select to authenticated using (status = 'PUBLICADA' or public.is_admin());
create policy "questions_admin_insert" on public.questions
for insert to authenticated with check (public.is_admin());
create policy "questions_admin_update" on public.questions
for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "questions_admin_delete" on public.questions
for delete to authenticated using (public.is_admin());

create policy "question_versions_admin_all" on public.question_versions
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- simulacros
create policy "simsets_read_published" on public.simulation_sets
for select to authenticated using (status = 'PUBLICADO' or public.is_admin());
create policy "simsets_admin_all" on public.simulation_sets
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "simq_read_published" on public.simulation_questions
for select to authenticated using (
  public.is_admin() or exists(
    select 1 from public.simulation_sets s
    where s.id = simulation_id and s.status = 'PUBLICADO'
  )
);
create policy "simq_admin_all" on public.simulation_questions
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- importaciones
create policy "imports_admin_all" on public.import_batches
for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "import_items_admin_all" on public.import_items
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- sesiones
create policy "sessions_own_or_admin" on public.study_sessions
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "sessions_insert_own" on public.study_sessions
for insert to authenticated with check (user_id = auth.uid());
create policy "sessions_update_own" on public.study_sessions
for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "attempts_own_or_admin" on public.attempts
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "attempts_insert_own" on public.attempts
for insert to authenticated with check (user_id = auth.uid() and public.can_answer_today());
create policy "attempts_update_own" on public.attempts
for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "favorites_own" on public.favorites
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "notes_own" on public.user_notes
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "reports_select_own_or_admin" on public.question_reports
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "reports_insert_own" on public.question_reports
for insert to authenticated with check (user_id = auth.uid());
create policy "reports_admin_update" on public.question_reports
for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "device_select_own_or_admin" on public.device_sessions
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "device_admin_all" on public.device_sessions
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------- Storage ----------
insert into storage.buckets (id, name, public)
values ('question-assets','question-assets', true)
on conflict (id) do update set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('import-files','import-files', false)
on conflict (id) do update set public = excluded.public;

create policy "question_assets_public_read" on storage.objects
for select using (bucket_id = 'question-assets');

create policy "question_assets_admin_write" on storage.objects
for insert to authenticated with check (bucket_id = 'question-assets' and public.is_admin());
create policy "question_assets_admin_update" on storage.objects
for update to authenticated using (bucket_id = 'question-assets' and public.is_admin())
with check (bucket_id = 'question-assets' and public.is_admin());
create policy "question_assets_admin_delete" on storage.objects
for delete to authenticated using (bucket_id = 'question-assets' and public.is_admin());

create policy "import_files_admin_read" on storage.objects
for select to authenticated using (bucket_id = 'import-files' and public.is_admin());
create policy "import_files_admin_write" on storage.objects
for insert to authenticated with check (bucket_id = 'import-files' and public.is_admin());
create policy "import_files_admin_delete" on storage.objects
for delete to authenticated using (bucket_id = 'import-files' and public.is_admin());

-- ---------- estadísticas útiles ----------
create or replace view public.v_question_stats
with (security_invoker = true)
as
select
  q.id as question_id,
  q.external_id,
  count(a.id)::integer as attempts,
  count(a.id) filter (where a.is_correct is true)::integer as correct,
  case when count(a.id) = 0 then null
       else round(100.0 * count(a.id) filter (where a.is_correct is true) / count(a.id), 1)
  end as accuracy_pct
from public.questions q
left join public.attempts a on a.question_id = q.id
where q.status = 'PUBLICADA' or public.is_admin()
group by q.id, q.external_id;

-- ---------- progreso seguro del alumno ----------
-- Evita que un estudiante pueda editar directamente role/plan/xp/streak en profiles.
create or replace function public.award_session_progress(p_session_id uuid)
returns jsonb
language plpgsql
security definer set search_path = public
as $$
declare
  uid uuid := auth.uid();
  sess public.study_sessions%rowtype;
  correct_n integer := 0;
  gain integer := 0;
  new_xp integer;
  new_streak integer;
begin
  if uid is null then raise exception 'No autenticado'; end if;

  select * into sess
  from public.study_sessions
  where id = p_session_id and user_id = uid
  for update;

  if sess.id is null then raise exception 'Sesión no encontrada'; end if;
  if sess.status <> 'COMPLETADA' then raise exception 'La sesión no está completada'; end if;

  if sess.xp_awarded then
    select xp, streak into new_xp, new_streak from public.profiles where id = uid;
    return jsonb_build_object('ok', true, 'already_awarded', true, 'xp', new_xp, 'streak', new_streak, 'gain', 0);
  end if;

  select count(*)::integer into correct_n
  from public.attempts
  where session_id = p_session_id and user_id = uid and is_correct is true;

  gain := correct_n * 2 + 5;

  update public.profiles
  set xp = xp + gain, streak = streak + 1, updated_at = now()
  where id = uid
  returning xp, streak into new_xp, new_streak;

  update public.study_sessions set xp_awarded = true where id = p_session_id;

  return jsonb_build_object('ok', true, 'already_awarded', false, 'xp', new_xp, 'streak', new_streak, 'gain', gain);
end;
$$;

grant execute on function public.award_session_progress(uuid) to authenticated;

-- ---------- función para reclamar un dispositivo ----------
create or replace function public.claim_device(p_device_id text, p_device_name text default null)
returns jsonb
language plpgsql
security definer set search_path = public
as $$
declare
  current_row public.device_sessions%rowtype;
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'No autenticado';
  end if;

  select * into current_row from public.device_sessions where user_id = uid;

  if current_row.user_id is null then
    insert into public.device_sessions(user_id, device_id, device_name)
    values(uid, p_device_id, p_device_name);
    return jsonb_build_object('ok', true, 'claimed', true);
  end if;

  if current_row.device_id = p_device_id then
    update public.device_sessions
      set last_seen_at = now(), device_name = coalesce(p_device_name, device_name)
      where user_id = uid;
    return jsonb_build_object('ok', true, 'claimed', false);
  end if;

  -- Permite cambiar de dispositivo si el anterior lleva 12 h sin actividad.
  if current_row.last_seen_at < now() - interval '12 hours' then
    update public.device_sessions
      set device_id = p_device_id, device_name = p_device_name, last_seen_at = now()
      where user_id = uid;
    return jsonb_build_object('ok', true, 'claimed', true, 'replaced_stale', true);
  end if;

  return jsonb_build_object(
    'ok', false,
    'reason', 'OTHER_DEVICE_ACTIVE',
    'device_name', current_row.device_name,
    'last_seen_at', current_row.last_seen_at
  );
end;
$$;

grant execute on function public.claim_device(text,text) to authenticated;

-- ---------- datos de referencia para Perú ----------
create table if not exists public.taxonomy (
  id bigint generated by default as identity primary key,
  exam_type text not null default 'RESIDENTADO',
  specialty text not null,
  topic text not null default '',
  subtopic text not null default '',
  active boolean not null default true,
  unique(exam_type, specialty, topic, subtopic)
);

alter table public.taxonomy enable row level security;
create policy "taxonomy_read" on public.taxonomy for select to authenticated using (active or public.is_admin());
create policy "taxonomy_admin_all" on public.taxonomy for all to authenticated using (public.is_admin()) with check (public.is_admin());

insert into public.taxonomy(exam_type, specialty, topic, subtopic) values
('RESIDENTADO','Medicina Interna','',''),
('RESIDENTADO','Cirugía','',''),
('RESIDENTADO','Pediatría','',''),
('RESIDENTADO','Ginecología y Obstetricia','',''),
('RESIDENTADO','Salud Pública y Gestión','',''),
('RESIDENTADO','Ciencias Básicas','',''),
('ENAM','Medicina Interna','',''),
('ENAM','Cirugía','',''),
('ENAM','Pediatría','',''),
('ENAM','Ginecología y Obstetricia','',''),
('ENAM','Salud Pública y Gestión','',''),
('ESSALUD','Medicina Interna','',''),
('ESSALUD','Cirugía','',''),
('ESSALUD','Pediatría','',''),
('ESSALUD','Ginecología y Obstetricia','',''),
('ESSALUD','Salud Pública y Gestión','','')
on conflict do nothing;
