-- BANQO Perú · esquema Supabase v1
-- Ejecutar completo en Supabase > SQL Editor.

create extension if not exists pgcrypto;

-- ---------- helpers ----------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------- perfiles ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'student' check (role in ('student','admin')),
  plan text not null default 'free' check (plan in ('free','pro','admin')),
  target_exam text default 'RESIDENTADO' check (target_exam in ('RESIDENTADO','ENAM','ESSALUD','TODOS')),
  stage text,
  xp integer not null default 0,
  streak integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  requested_target text;
begin
  requested_target := upper(coalesce(new.raw_user_meta_data ->> 'target_exam', 'RESIDENTADO'));
  if requested_target not in ('RESIDENTADO','ENAM','ESSALUD','TODOS') then
    requested_target := 'RESIDENTADO';
  end if;

  insert into public.profiles (id, full_name, target_exam)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''), requested_target)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists(
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$;

-- ---------- preguntas ----------
create table if not exists public.questions (
  id uuid primary key default gen_random_uuid(),
  external_id text not null unique,
  bank_type text not null default 'BANCO' check (bank_type in ('BANCO','SIMULACRO','PREGUNTA_SUELTA')),
  exam_type text not null default 'RESIDENTADO' check (exam_type in ('RESIDENTADO','ENAM','ESSALUD','OTRO')),
  bank_name text not null default 'BANQO',
  year integer,
  specialty text not null default 'Sin clasificar',
  topic text not null default 'Sin clasificar',
  subtopic text not null default 'Sin clasificar',
  section text not null default '',
  stem text not null,
  options jsonb not null default '{}'::jsonb,
  correct_answer text check (correct_answer is null or correct_answer in ('A','B','C','D','E')),
  explanation text not null default '',
  galactic_tip text not null default '',
  source_reference text not null default '',
  source_page integer,
  requires_image boolean not null default false,
  image_url text,
  status text not null default 'PENDIENTE' check (status in ('PENDIENTE','APROBADA','PUBLICADA','ARCHIVADA')),
  review_notes text not null default '',
  source_uid text,
  source_hash text,
  version integer not null default 1,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint questions_options_object check (jsonb_typeof(options) = 'object')
);

create index if not exists idx_questions_status on public.questions(status);
create index if not exists idx_questions_exam on public.questions(exam_type);
create index if not exists idx_questions_bank on public.questions(bank_name);
create index if not exists idx_questions_taxonomy on public.questions(specialty, topic, subtopic);
create index if not exists idx_questions_source_uid on public.questions(source_uid);

-- Historial editorial: conserva la versión previa cuando una importación modifica una pregunta.
create table if not exists public.question_versions (
  id bigint generated by default as identity primary key,
  question_id uuid not null references public.questions(id) on delete cascade,
  version integer not null,
  snapshot jsonb not null,
  changed_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique(question_id, version)
);

create index if not exists idx_question_versions_question on public.question_versions(question_id, version desc);

create trigger questions_set_updated_at
before update on public.questions
for each row execute procedure public.set_updated_at();

-- ---------- simulacros ----------
create table if not exists public.simulation_sets (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  exam_type text not null default 'RESIDENTADO' check (exam_type in ('RESIDENTADO','ENAM','ESSALUD','OTRO')),
  year integer,
  description text not null default '',
  duration_minutes integer,
  question_count integer not null default 0,
  status text not null default 'BORRADOR' check (status in ('BORRADOR','PUBLICADO','ARCHIVADO')),
  source_reference text not null default '',
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger simulation_sets_set_updated_at
before update on public.simulation_sets
for each row execute procedure public.set_updated_at();

create table if not exists public.simulation_questions (
  simulation_id uuid not null references public.simulation_sets(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  order_no integer not null,
  is_reserve boolean not null default false,
  primary key (simulation_id, question_id),
  unique (simulation_id, order_no)
);

-- ---------- importaciones admin ----------
create table if not exists public.import_batches (
  id uuid primary key default gen_random_uuid(),
  import_type text not null check (import_type in ('XLSX','CSV','JSON','PDF_RESALTADO')),
  bank_type text not null default 'BANCO' check (bank_type in ('BANCO','SIMULACRO','PREGUNTA_SUELTA')),
  exam_type text not null default 'RESIDENTADO' check (exam_type in ('RESIDENTADO','ENAM','ESSALUD','OTRO')),
  name text not null,
  file_name text,
  storage_path text,
  status text not null default 'PREVISUALIZADO' check (status in ('PREVISUALIZADO','IMPORTANDO','COMPLETADO','CON_ERRORES','CANCELADO')),
  total_rows integer not null default 0,
  valid_rows integer not null default 0,
  error_rows integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  report jsonb not null default '{}'::jsonb,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger import_batches_set_updated_at
before update on public.import_batches
for each row execute procedure public.set_updated_at();

create table if not exists public.import_items (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.import_batches(id) on delete cascade,
  row_number integer,
  external_id text,
  raw_data jsonb not null default '{}'::jsonb,
  normalized_data jsonb not null default '{}'::jsonb,
  status text not null default 'PENDIENTE' check (status in ('PENDIENTE','VALIDO','ERROR','IMPORTADO','OMITIDO')),
  errors jsonb not null default '[]'::jsonb,
  linked_question_id uuid references public.questions(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_import_items_batch on public.import_items(batch_id);

-- ---------- sesiones y respuestas ----------
create table if not exists public.study_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  session_type text not null check (session_type in ('PRACTICE','SIMULATION','DIAGNOSTIC')),
  simulation_id uuid references public.simulation_sets(id),
  filters jsonb not null default '{}'::jsonb,
  question_ids uuid[] not null default '{}'::uuid[],
  status text not null default 'EN_CURSO' check (status in ('EN_CURSO','COMPLETADA','ABANDONADA')),
  correct_count integer not null default 0,
  incorrect_count integer not null default 0,
  blank_count integer not null default 0,
  score numeric(6,2),
  elapsed_seconds integer not null default 0,
  xp_awarded boolean not null default false,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists idx_sessions_user on public.study_sessions(user_id, started_at desc);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.study_sessions(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  selected_answer text check (selected_answer is null or selected_answer in ('A','B','C','D','E')),
  is_correct boolean,
  marked boolean not null default false,
  discarded_options text[] not null default '{}'::text[],
  response_ms integer,
  answered_at timestamptz not null default now(),
  unique(session_id, question_id)
);

create index if not exists idx_attempts_user on public.attempts(user_id, answered_at desc);
create index if not exists idx_attempts_question on public.attempts(question_id);

create table if not exists public.favorites (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id, question_id)
);

create table if not exists public.user_notes (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  note text not null default '',
  updated_at timestamptz not null default now(),
  primary key(user_id, question_id)
);

create trigger user_notes_set_updated_at
before update on public.user_notes
for each row execute procedure public.set_updated_at();

create table if not exists public.question_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  reason text not null,
  comment text not null default '',
  status text not null default 'PENDIENTE' check (status in ('PENDIENTE','REVISADO','RESUELTO','DESCARTADO')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger question_reports_set_updated_at
before update on public.question_reports
for each row execute procedure public.set_updated_at();

-- ---------- dispositivo (base para 1 dispositivo por cuenta) ----------
create table if not exists public.device_sessions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  device_id text not null,
  device_name text,
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger device_sessions_set_updated_at
before update on public.device_sessions
for each row execute procedure public.set_updated_at();

-- ---------- límites del plan gratuito (servidor) ----------
create or replace function public.free_questions_remaining()
returns integer
language plpgsql
stable
security definer set search_path = public
as $$
declare
  uid uuid := auth.uid();
  p public.profiles%rowtype;
  used_n integer;
begin
  if uid is null then raise exception 'No autenticado'; end if;
  select * into p from public.profiles where id = uid;
  if p.role = 'admin' or p.plan in ('pro','admin') then return -1; end if;
  select count(*)::integer into used_n
  from public.attempts
  where user_id = uid
    and (answered_at at time zone 'America/Lima')::date = (now() at time zone 'America/Lima')::date;
  return greatest(0, 15 - used_n);
end;
$$;

create or replace function public.can_answer_today()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select public.free_questions_remaining() <> 0;
$$;

grant execute on function public.free_questions_remaining() to authenticated;
grant execute on function public.can_answer_today() to authenticated;

-- El cliente nunca debe poder resetear xp_awarded para cobrar XP dos veces.
create or replace function public.protect_study_session_internal()
returns trigger
language plpgsql
as $$
begin
  if current_user = 'authenticated' then
    new.xp_awarded := old.xp_awarded;
  end if;
  return new;
end;
$$;

drop trigger if exists protect_study_session_internal_fields on public.study_sessions;
create trigger protect_study_session_internal_fields
before update on public.study_sessions
for each row execute procedure public.protect_study_session_internal();

-- ---------- RLS ----------
alter table public.profiles enable row level security;
alter table public.questions enable row level security;
alter table public.question_versions enable row level security;
alter table public.simulation_sets enable row level security;
alter table public.simulation_questions enable row level security;
alter table public.import_batches enable row level security;
alter table public.import_items enable row level security;
alter table public.study_sessions enable row level security;
alter table public.attempts enable row level security;
alter table public.favorites enable row level security;
alter table public.user_notes enable row level security;
alter table public.question_reports enable row level security;
alter table public.device_sessions enable row level security;

-- perfiles
-- El alumno puede leer su propio perfil, pero NO puede elevar su rol/plan desde el navegador.
create policy "profiles_select_own_or_admin" on public.profiles
for select to authenticated using (id = auth.uid() or public.is_admin());
create policy "profiles_insert_self_student" on public.profiles
for insert to authenticated
with check (id = auth.uid() and role = 'student' and plan = 'free');
create policy "profiles_admin_update" on public.profiles
for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- preguntas
create policy "questions_read_published" on public.questions
for select to authenticated using (status = 'PUBLICADA' or public.is_admin());
create policy "questions_admin_insert" on public.questions
for insert to authenticated with check (public.is_admin());
create policy "questions_admin_update" on public.questions
for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "questions_admin_delete" on public.questions
for delete to authenticated using (public.is_admin());

create policy "question_versions_admin_all" on public.question_versions
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- simulacros
create policy "simsets_read_published" on public.simulation_sets
for select to authenticated using (status = 'PUBLICADO' or public.is_admin());
create policy "simsets_admin_all" on public.simulation_sets
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "simq_read_published" on public.simulation_questions
for select to authenticated using (
  public.is_admin() or exists(
    select 1 from public.simulation_sets s
    where s.id = simulation_id and s.status = 'PUBLICADO'
  )
);
create policy "simq_admin_all" on public.simulation_questions
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- importaciones
create policy "imports_admin_all" on public.import_batches
for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "import_items_admin_all" on public.import_items
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- sesiones
create policy "sessions_own_or_admin" on public.study_sessions
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "sessions_insert_own" on public.study_sessions
for insert to authenticated with check (user_id = auth.uid());
create policy "sessions_update_own" on public.study_sessions
for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "attempts_own_or_admin" on public.attempts
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "attempts_insert_own" on public.attempts
for insert to authenticated with check (user_id = auth.uid() and public.can_answer_today());
create policy "attempts_update_own" on public.attempts
for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "favorites_own" on public.favorites
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "notes_own" on public.user_notes
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "reports_select_own_or_admin" on public.question_reports
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "reports_insert_own" on public.question_reports
for insert to authenticated with check (user_id = auth.uid());
create policy "reports_admin_update" on public.question_reports
for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "device_select_own_or_admin" on public.device_sessions
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "device_admin_all" on public.device_sessions
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------- Storage ----------
insert into storage.buckets (id, name, public)
values ('question-assets','question-assets', true)
on conflict (id) do update set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('import-files','import-files', false)
on conflict (id) do update set public = excluded.public;

create policy "question_assets_public_read" on storage.objects
for select using (bucket_id = 'question-assets');

create policy "question_assets_admin_write" on storage.objects
for insert to authenticated with check (bucket_id = 'question-assets' and public.is_admin());
create policy "question_assets_admin_update" on storage.objects
for update to authenticated using (bucket_id = 'question-assets' and public.is_admin())
with check (bucket_id = 'question-assets' and public.is_admin());
create policy "question_assets_admin_delete" on storage.objects
for delete to authenticated using (bucket_id = 'question-assets' and public.is_admin());

create policy "import_files_admin_read" on storage.objects
for select to authenticated using (bucket_id = 'import-files' and public.is_admin());
create policy "import_files_admin_write" on storage.objects
for insert to authenticated with check (bucket_id = 'import-files' and public.is_admin());
create policy "import_files_admin_delete" on storage.objects
for delete to authenticated using (bucket_id = 'import-files' and public.is_admin());

-- ---------- estadísticas útiles ----------
create or replace view public.v_question_stats
with (security_invoker = true)
as
select
  q.id as question_id,
  q.external_id,
  count(a.id)::integer as attempts,
  count(a.id) filter (where a.is_correct is true)::integer as correct,
  case when count(a.id) = 0 then null
       else round(100.0 * count(a.id) filter (where a.is_correct is true) / count(a.id), 1)
  end as accuracy_pct
from public.questions q
left join public.attempts a on a.question_id = q.id
where q.status = 'PUBLICADA' or public.is_admin()
group by q.id, q.external_id;

-- ---------- progreso seguro del alumno ----------
-- Evita que un estudiante pueda editar directamente role/plan/xp/streak en profiles.
create or replace function public.award_session_progress(p_session_id uuid)
returns jsonb
language plpgsql
security definer set search_path = public
as $$
declare
  uid uuid := auth.uid();
  sess public.study_sessions%rowtype;
  correct_n integer := 0;
  gain integer := 0;
  new_xp integer;
  new_streak integer;
begin
  if uid is null then raise exception 'No autenticado'; end if;

  select * into sess
  from public.study_sessions
  where id = p_session_id and user_id = uid
  for update;

  if sess.id is null then raise exception 'Sesión no encontrada'; end if;
  if sess.status <> 'COMPLETADA' then raise exception 'La sesión no está completada'; end if;

  if sess.xp_awarded then
    select xp, streak into new_xp, new_streak from public.profiles where id = uid;
    return jsonb_build_object('ok', true, 'already_awarded', true, 'xp', new_xp, 'streak', new_streak, 'gain', 0);
  end if;

  select count(*)::integer into correct_n
  from public.attempts
  where session_id = p_session_id and user_id = uid and is_correct is true;

  gain := correct_n * 2 + 5;

  update public.profiles
  set xp = xp + gain, streak = streak + 1, updated_at = now()
  where id = uid
  returning xp, streak into new_xp, new_streak;

  update public.study_sessions set xp_awarded = true where id = p_session_id;

  return jsonb_build_object('ok', true, 'already_awarded', false, 'xp', new_xp, 'streak', new_streak, 'gain', gain);
end;
$$;

grant execute on function public.award_session_progress(uuid) to authenticated;

-- ---------- función para reclamar un dispositivo ----------
create or replace function public.claim_device(p_device_id text, p_device_name text default null)
returns jsonb
language plpgsql
security definer set search_path = public
as $$
declare
  current_row public.device_sessions%rowtype;
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'No autenticado';
  end if;

  select * into current_row from public.device_sessions where user_id = uid;

  if current_row.user_id is null then
    insert into public.device_sessions(user_id, device_id, device_name)
    values(uid, p_device_id, p_device_name);
    return jsonb_build_object('ok', true, 'claimed', true);
  end if;

  if current_row.device_id = p_device_id then
    update public.device_sessions
      set last_seen_at = now(), device_name = coalesce(p_device_name, device_name)
      where user_id = uid;
    return jsonb_build_object('ok', true, 'claimed', false);
  end if;

  -- Permite cambiar de dispositivo si el anterior lleva 12 h sin actividad.
  if current_row.last_seen_at < now() - interval '12 hours' then
    update public.device_sessions
      set device_id = p_device_id, device_name = p_device_name, last_seen_at = now()
      where user_id = uid;
    return jsonb_build_object('ok', true, 'claimed', true, 'replaced_stale', true);
  end if;

  return jsonb_build_object(
    'ok', false,
    'reason', 'OTHER_DEVICE_ACTIVE',
    'device_name', current_row.device_name,
    'last_seen_at', current_row.last_seen_at
  );
end;
$$;

grant execute on function public.claim_device(text,text) to authenticated;

-- ---------- datos de referencia para Perú ----------
create table if not exists public.taxonomy (
  id bigint generated by default as identity primary key,
  exam_type text not null default 'RESIDENTADO',
  specialty text not null,
  topic text not null default '',
  subtopic text not null default '',
  active boolean not null default true,
  unique(exam_type, specialty, topic, subtopic)
);

alter table public.taxonomy enable row level security;
create policy "taxonomy_read" on public.taxonomy for select to authenticated using (active or public.is_admin());
create policy "taxonomy_admin_all" on public.taxonomy for all to authenticated using (public.is_admin()) with check (public.is_admin());

insert into public.taxonomy(exam_type, specialty, topic, subtopic) values
('RESIDENTADO','Medicina Interna','',''),
('RESIDENTADO','Cirugía','',''),
('RESIDENTADO','Pediatría','',''),
('RESIDENTADO','Ginecología y Obstetricia','',''),
('RESIDENTADO','Salud Pública y Gestión','',''),
('RESIDENTADO','Ciencias Básicas','',''),
('ENAM','Medicina Interna','',''),
('ENAM','Cirugía','',''),
('ENAM','Pediatría','',''),
('ENAM','Ginecología y Obstetricia','',''),
('ENAM','Salud Pública y Gestión','',''),
('ESSALUD','Medicina Interna','',''),
('ESSALUD','Cirugía','',''),
('ESSALUD','Pediatría','',''),
('ESSALUD','Ginecología y Obstetricia','',''),
('ESSALUD','Salud Pública y Gestión','','')
on conflict do nothing;

-- ---------- v1.6: correcciones de auditoría ----------
-- El bloque siguiente también existe como migración independiente en
-- supabase/v1_6_audit_fix.sql para instalaciones anteriores.
-- BANQO Perú · actualización v1.6 (correcciones de auditoría)
-- Ejecutar UNA VEZ en Supabase > SQL Editor para proyectos existentes.
-- Es aditiva: no borra preguntas, usuarios ni progreso.

begin;

-- Roles y metadatos editoriales.
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('student','moderator','admin'));

alter table public.questions add column if not exists explanation_source text not null default 'MANUAL';
alter table public.questions drop constraint if exists questions_explanation_source_check;
alter table public.questions add constraint questions_explanation_source_check
  check (explanation_source in ('MANUAL','AUTO_LOCAL','IA'));

alter table public.simulation_sets add column if not exists penalty numeric(6,3) not null default 0.333;

create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role in ('moderator','admin'));
$$;

-- Ajustes por usuario, sin números fijos repetidos en el cliente.
create table if not exists public.app_settings(
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);
insert into public.app_settings(key,value) values ('free_daily_questions','15'::jsonb)
on conflict (key) do nothing;
alter table public.app_settings enable row level security;
drop policy if exists "settings_read" on public.app_settings;
create policy "settings_read" on public.app_settings for select to authenticated using (true);
drop policy if exists "settings_admin_all" on public.app_settings;
create policy "settings_admin_all" on public.app_settings for all to authenticated
using (public.is_admin()) with check (public.is_admin());

create or replace function public.free_questions_remaining()
returns integer language plpgsql stable security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles%rowtype; used_n integer; daily_limit integer:=15;
begin
  if uid is null then raise exception 'No autenticado'; end if;
  select * into p from public.profiles where id=uid;
  if p.role in ('admin','moderator') or p.plan in ('pro','admin') then return -1; end if;
  select coalesce((value #>> '{}')::integer,15) into daily_limit
  from public.app_settings where key='free_daily_questions';
  select count(*)::integer into used_n from public.attempts
  where user_id=uid and selected_answer is not null
    and (answered_at at time zone 'America/Lima')::date=(now() at time zone 'America/Lima')::date;
  return greatest(0,coalesce(daily_limit,15)-used_n);
end; $$;

-- Resaltados guardados como offsets de texto, nunca como HTML.
create table if not exists public.user_highlights(
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  start_offset integer not null check(start_offset>=0),
  end_offset integer not null check(end_offset>start_offset),
  color text not null default 'yellow' check(color in ('yellow','green','blue','pink')),
  created_at timestamptz not null default now(),
  unique(user_id,question_id,start_offset,end_offset)
);
alter table public.user_highlights enable row level security;
drop policy if exists "highlights_own" on public.user_highlights;
create policy "highlights_own" on public.user_highlights for all to authenticated
using(user_id=auth.uid()) with check(user_id=auth.uid());

-- Estado de pregunta no contestada (marcada/descartes) sin consumir cupo Free.
create table if not exists public.study_question_state(
  session_id uuid not null references public.study_sessions(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  marked boolean not null default false,
  discarded_options text[] not null default '{}'::text[],
  updated_at timestamptz not null default now(),
  primary key(session_id,question_id)
);
alter table public.study_question_state enable row level security;
drop policy if exists "study_question_state_own" on public.study_question_state;
create policy "study_question_state_own" on public.study_question_state for all to authenticated
using(user_id=auth.uid()) with check(user_id=auth.uid());

-- Perfil: el alumno puede editar datos propios sin elevar rol, plan, XP o racha.
create or replace function public.protect_profile_privileges()
returns trigger language plpgsql set search_path=public as $$
begin
  if old.role='admin' and new.role<>'admin' and (select count(*) from public.profiles where role='admin')<=1 then
    raise exception 'No puedes quitar el rol al último administrador';
  end if;
  if auth.uid()=old.id and not public.is_admin() then
    new.role:=old.role; new.plan:=old.plan; new.xp:=old.xp; new.streak:=old.streak;
  end if;
  return new;
end; $$;
drop trigger if exists protect_profile_privileges_trigger on public.profiles;
create trigger protect_profile_privileges_trigger before update on public.profiles
for each row execute function public.protect_profile_privileges();
drop policy if exists "profiles_update_own_safe" on public.profiles;
create policy "profiles_update_own_safe" on public.profiles for update to authenticated
using(id=auth.uid()) with check(id=auth.uid());

-- Staff puede revisar; sólo admin importa, elimina y publica.
drop policy if exists "questions_read_published" on public.questions;
create policy "questions_read_published" on public.questions for select to authenticated
using(status='PUBLICADA' or public.is_staff());
drop policy if exists "questions_staff_update" on public.questions;
create policy "questions_staff_update" on public.questions for update to authenticated
using(public.is_staff()) with check(public.is_staff());
drop policy if exists "question_versions_admin_all" on public.question_versions;
create policy "question_versions_staff_all" on public.question_versions for all to authenticated
using(public.is_staff()) with check(public.is_staff());
drop policy if exists "simsets_read_published" on public.simulation_sets;
create policy "simsets_read_published_or_staff" on public.simulation_sets for select to authenticated
using(status='PUBLICADO' or public.is_staff());
drop policy if exists "simq_read_published" on public.simulation_questions;
create policy "simq_read_published_or_staff" on public.simulation_questions for select to authenticated
using(public.is_staff() or exists(select 1 from public.simulation_sets s where s.id=simulation_id and s.status='PUBLICADO'));
drop policy if exists "reports_select_own_or_admin" on public.question_reports;
create policy "reports_select_own_or_staff" on public.question_reports for select to authenticated
using(user_id=auth.uid() or public.is_staff());
drop policy if exists "reports_admin_update" on public.question_reports;
create policy "reports_staff_update" on public.question_reports for update to authenticated
using(public.is_staff()) with check(public.is_staff());

create or replace function public.protect_question_publication()
returns trigger language plpgsql set search_path=public as $$
begin
  if old.status is distinct from new.status and (old.status='PUBLICADA' or new.status='PUBLICADA') and not public.is_admin() then
    raise exception 'Sólo un administrador puede publicar o retirar preguntas' using errcode='42501';
  end if;
  return new;
end; $$;
drop trigger if exists protect_question_publication_trigger on public.questions;
create trigger protect_question_publication_trigger before update on public.questions
for each row execute function public.protect_question_publication();

-- El moderador puede corregir y adjuntar recursos, pero no eliminar archivos.
drop policy if exists "question_assets_admin_write" on storage.objects;
drop policy if exists "question_assets_admin_update" on storage.objects;
drop policy if exists "question_assets_staff_write" on storage.objects;
drop policy if exists "question_assets_staff_update" on storage.objects;
create policy "question_assets_staff_write" on storage.objects for insert to authenticated
with check(bucket_id='question-assets' and public.is_staff());
create policy "question_assets_staff_update" on storage.objects for update to authenticated
using(bucket_id='question-assets' and public.is_staff()) with check(bucket_id='question-assets' and public.is_staff());

-- Una simulación sólo puede publicarse si todas sus preguntas activas están publicadas.
create or replace function public.simulation_readiness(p_sim uuid)
returns jsonb language sql stable security definer set search_path=public as $$
  select jsonb_build_object(
    'total',count(*) filter(where not sq.is_reserve),
    'published',count(*) filter(where not sq.is_reserve and q.status='PUBLICADA'),
    'pending',count(*) filter(where not sq.is_reserve and q.status<>'PUBLICADA')
  ) from public.simulation_questions sq join public.questions q on q.id=sq.question_id
  where sq.simulation_id=p_sim;
$$;
grant execute on function public.simulation_readiness(uuid) to authenticated;

create or replace function public.publish_simulation_questions(p_sim uuid)
returns integer language plpgsql security definer set search_path=public as $$
declare n integer;
begin
  if not public.is_admin() then raise exception 'No autorizado' using errcode='42501'; end if;
  update public.questions q set status='PUBLICADA',updated_by=auth.uid()
  from public.simulation_questions sq
  where sq.simulation_id=p_sim and sq.question_id=q.id and not sq.is_reserve
    and q.status in ('PENDIENTE','APROBADA');
  get diagnostics n=row_count; return n;
end; $$;
grant execute on function public.publish_simulation_questions(uuid) to authenticated;

-- JSON seguro: mientras una sesión está en curso, nunca entrega clave/explicación.
create or replace function public.safe_question(q public.questions)
returns jsonb language sql immutable as $$
  select to_jsonb(q)-array['correct_answer','explanation','galactic_tip','review_notes','created_by','updated_by','source_hash'];
$$;

create or replace function public.start_practice(
  p_count integer, p_mode text, p_filters jsonb default '{}'::jsonb, p_random boolean default true,
  p_question_ids uuid[] default null
) returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); ids uuid[]; sid uuid; qs jsonb; allowed integer; requested integer;
begin
  if uid is null then raise exception 'No autenticado'; end if;
  requested:=greatest(1,least(coalesce(p_count,15),100)); allowed:=public.free_questions_remaining();
  if allowed=0 then raise exception 'FREE_LIMIT_REACHED' using errcode='P0001'; end if;
  if allowed>=0 then requested:=least(requested,allowed); end if;
  if p_mode not in ('instant','exam') then p_mode:='instant'; end if;

  if p_question_ids is not null then
    select array_agg(x.id order by array_position(p_question_ids,x.id)) into ids from (
      select id from public.questions where id=any(p_question_ids) and status='PUBLICADA'
      order by array_position(p_question_ids,id) limit requested
    ) x;
  elsif p_random then
    select array_agg(id) into ids from (
      select id from public.questions q where q.status='PUBLICADA'
      and (coalesce(p_filters->>'exam','')='' or q.exam_type=p_filters->>'exam')
      and (coalesce(p_filters->>'bank','')='' or q.bank_name=p_filters->>'bank')
      and (coalesce(p_filters->>'specialty','')='' or q.specialty=p_filters->>'specialty')
      and (coalesce(p_filters->>'topic','')='' or q.topic=p_filters->>'topic')
      and (coalesce(p_filters->>'subtopic','')='' or q.subtopic=p_filters->>'subtopic')
      order by random() limit requested
    ) x;
  else
    select array_agg(id) into ids from (
      select id from public.questions q where q.status='PUBLICADA'
      and (coalesce(p_filters->>'exam','')='' or q.exam_type=p_filters->>'exam')
      and (coalesce(p_filters->>'bank','')='' or q.bank_name=p_filters->>'bank')
      and (coalesce(p_filters->>'specialty','')='' or q.specialty=p_filters->>'specialty')
      and (coalesce(p_filters->>'topic','')='' or q.topic=p_filters->>'topic')
      and (coalesce(p_filters->>'subtopic','')='' or q.subtopic=p_filters->>'subtopic')
      order by q.external_id limit requested
    ) x;
  end if;
  if coalesce(array_length(ids,1),0)=0 then raise exception 'NO_QUESTIONS' using errcode='P0001'; end if;
  insert into public.study_sessions(user_id,session_type,filters,question_ids)
  values(uid,'PRACTICE',coalesce(p_filters,'{}'::jsonb)||jsonb_build_object('answer_mode',p_mode),ids)
  returning id into sid;
  select jsonb_agg(public.safe_question(q) order by array_position(ids,q.id)) into qs
  from public.questions q where q.id=any(ids);
  return jsonb_build_object('session_id',sid,'questions',coalesce(qs,'[]'::jsonb),'allowed',allowed);
end; $$;
grant execute on function public.start_practice(integer,text,jsonb,boolean,uuid[]) to authenticated;

create or replace function public.start_simulation(p_sim uuid,p_mode text default 'exam')
returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); sim public.simulation_sets%rowtype; ids uuid[]; sid uuid; qs jsonb; allowed integer;
begin
  if uid is null then raise exception 'No autenticado'; end if;
  select * into sim from public.simulation_sets where id=p_sim and status='PUBLICADO';
  if sim.id is null then raise exception 'SIMULATION_NOT_AVAILABLE' using errcode='P0001'; end if;
  select array_agg(sq.question_id order by sq.order_no) into ids
  from public.simulation_questions sq join public.questions q on q.id=sq.question_id
  where sq.simulation_id=p_sim and not sq.is_reserve and q.status='PUBLICADA';
  if coalesce(array_length(ids,1),0)<>sim.question_count then raise exception 'SIMULATION_NOT_READY' using errcode='P0001'; end if;
  allowed:=public.free_questions_remaining();
  if allowed>=0 and allowed<array_length(ids,1) then raise exception 'FREE_SIMULATION_LIMIT' using errcode='P0001'; end if;
  if p_mode not in ('instant','exam') then p_mode:='exam'; end if;
  insert into public.study_sessions(user_id,session_type,simulation_id,filters,question_ids)
  values(uid,'SIMULATION',sim.id,jsonb_build_object('name',sim.name,'answer_mode',p_mode),ids) returning id into sid;
  select jsonb_agg(public.safe_question(q) order by array_position(ids,q.id)) into qs
  from public.questions q where q.id=any(ids);
  return jsonb_build_object('session_id',sid,'simulation',to_jsonb(sim),'questions',qs);
end; $$;
grant execute on function public.start_simulation(uuid,text) to authenticated;

create or replace function public.resume_study_session(p_session uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); s public.study_sessions%rowtype; qs jsonb; ans jsonb; st jsonb;
begin
  select * into s from public.study_sessions where id=p_session and user_id=uid;
  if s.id is null then raise exception 'Sesión no encontrada'; end if;
  if s.status='COMPLETADA' then
    select jsonb_agg(((to_jsonb(q)-array['review_notes','source_hash','created_by','updated_by'])||jsonb_build_object('explanation',case when q.explanation_source='AUTO_LOCAL' then '' else q.explanation end,'galactic_tip',case when q.explanation_source='AUTO_LOCAL' then '' else q.galactic_tip end)) order by array_position(s.question_ids,q.id)) into qs from public.questions q where q.id=any(s.question_ids);
  else
    select jsonb_agg(public.safe_question(q) order by array_position(s.question_ids,q.id)) into qs from public.questions q where q.id=any(s.question_ids);
  end if;
  select coalesce(jsonb_object_agg(question_id::text,selected_answer) filter(where selected_answer is not null),'{}'::jsonb) into ans
  from public.attempts where session_id=s.id and user_id=uid;
  select coalesce(jsonb_object_agg(question_id::text,jsonb_build_object('marked',marked,'discarded',discarded_options)),'{}'::jsonb) into st
  from public.study_question_state where session_id=s.id and user_id=uid;
  return jsonb_build_object('session',to_jsonb(s),'questions',coalesce(qs,'[]'::jsonb),'answers',ans,'question_state',st);
end; $$;
grant execute on function public.resume_study_session(uuid) to authenticated;

create or replace function public.save_question_state(p_session uuid,p_question uuid,p_marked boolean,p_discarded text[])
returns void language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid();
begin
  if not exists(select 1 from public.study_sessions where id=p_session and user_id=uid and status='EN_CURSO' and p_question=any(question_ids))
    then raise exception 'Sesión no válida' using errcode='42501'; end if;
  insert into public.study_question_state(session_id,user_id,question_id,marked,discarded_options)
  values(p_session,uid,p_question,coalesce(p_marked,false),coalesce(p_discarded,'{}'::text[]))
  on conflict(session_id,question_id) do update set marked=excluded.marked,discarded_options=excluded.discarded_options,updated_at=now();
end; $$;
grant execute on function public.save_question_state(uuid,uuid,boolean,text[]) to authenticated;

create or replace function public.answer_question(
  p_session uuid,p_question uuid,p_letter text,p_marked boolean default false,
  p_discarded text[] default '{}'::text[],p_response_ms integer default null
) returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); s public.study_sessions%rowtype; q public.questions%rowtype; ok boolean; mode text; remaining integer;
begin
  if uid is null then raise exception 'No autenticado'; end if;
  perform pg_advisory_xact_lock(hashtext(uid::text));
  select * into s from public.study_sessions where id=p_session and user_id=uid and status='EN_CURSO' for update;
  if s.id is null or not p_question=any(s.question_ids) then raise exception 'Sesión no válida' using errcode='42501'; end if;
  if upper(p_letter) not in ('A','B','C','D','E') then raise exception 'Respuesta no válida'; end if;
  if not exists(select 1 from public.attempts where session_id=p_session and question_id=p_question and selected_answer is not null) then
    remaining:=public.free_questions_remaining();
    if remaining=0 then raise exception 'FREE_LIMIT_REACHED' using errcode='P0001'; end if;
  end if;
  select * into q from public.questions where id=p_question;
  ok:=upper(p_letter)=q.correct_answer; mode:=coalesce(s.filters->>'answer_mode','instant');
  insert into public.attempts(session_id,user_id,question_id,selected_answer,is_correct,marked,discarded_options,response_ms,answered_at)
  values(p_session,uid,p_question,upper(p_letter),ok,coalesce(p_marked,false),coalesce(p_discarded,'{}'::text[]),greatest(0,p_response_ms),now())
  on conflict(session_id,question_id) do update set selected_answer=excluded.selected_answer,is_correct=excluded.is_correct,
    marked=excluded.marked,discarded_options=excluded.discarded_options,response_ms=excluded.response_ms,answered_at=now();
  perform public.save_question_state(p_session,p_question,p_marked,p_discarded);
  if mode='instant' then
    return jsonb_build_object('ok',true,'is_correct',ok,'correct_answer',q.correct_answer,
      'explanation',case when q.explanation_source='AUTO_LOCAL' then '' else q.explanation end,
      'galactic_tip',case when q.explanation_source='AUTO_LOCAL' then '' else q.galactic_tip end);
  end if;
  return jsonb_build_object('ok',true);
end; $$;
grant execute on function public.answer_question(uuid,uuid,text,boolean,text[],integer) to authenticated;

create or replace function public.complete_study_session(p_session uuid,p_elapsed integer default 0)
returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); s public.study_sessions%rowtype; total integer; correct_n integer; incorrect_n integer; blank_n integer; score_n numeric; qs jsonb;
begin
  select * into s from public.study_sessions where id=p_session and user_id=uid for update;
  if s.id is null then raise exception 'Sesión no encontrada' using errcode='42501'; end if;
  total:=coalesce(array_length(s.question_ids,1),0);
  select count(*) filter(where is_correct is true),count(*) filter(where selected_answer is not null and is_correct is false)
    into correct_n,incorrect_n from public.attempts where session_id=s.id and user_id=uid;
  blank_n:=greatest(0,total-correct_n-incorrect_n); score_n:=case when total=0 then 0 else round(correct_n*100.0/total,2) end;
  update public.study_sessions set status='COMPLETADA',correct_count=correct_n,incorrect_count=incorrect_n,
    blank_count=blank_n,score=score_n,elapsed_seconds=greatest(0,p_elapsed),finished_at=coalesce(finished_at,now()) where id=s.id;
  select jsonb_agg(((to_jsonb(q)-array['review_notes','source_hash','created_by','updated_by'])||jsonb_build_object('explanation',case when q.explanation_source='AUTO_LOCAL' then '' else q.explanation end,
    'galactic_tip',case when q.explanation_source='AUTO_LOCAL' then '' else q.galactic_tip end)) order by array_position(s.question_ids,q.id))
    into qs from public.questions q where q.id=any(s.question_ids);
  return jsonb_build_object('correct',correct_n,'incorrect',incorrect_n,'blank',blank_n,'score',score_n,'questions',coalesce(qs,'[]'::jsonb));
end; $$;
grant execute on function public.complete_study_session(uuid,integer) to authenticated;

-- Taxonomía y progreso sin descargar miles de filas completas.
create or replace view public.v_active_taxonomy with(security_invoker=true) as
select exam_type,bank_name,specialty,topic,subtopic,count(*)::integer available
from public.questions where status='PUBLICADA' group by 1,2,3,4,5;

create or replace view public.v_user_topic_progress with(security_invoker=true) as
select a.user_id,q.specialty,q.topic,count(*)::integer total,
  count(*) filter(where a.is_correct is true)::integer correct,
  round(100.0*count(*) filter(where a.is_correct is true)/nullif(count(*),0),1) accuracy_pct
from public.attempts a join public.questions q on q.id=a.question_id
group by a.user_id,q.specialty,q.topic;
grant select on public.v_active_taxonomy,public.v_user_topic_progress to authenticated;

-- Administración de usuarios sin exponer auth.users a estudiantes.

-- Sesiones y respuestas sólo se escriben mediante RPC validadas en servidor.
drop policy if exists "sessions_insert_own" on public.study_sessions;
drop policy if exists "sessions_update_own" on public.study_sessions;
drop policy if exists "attempts_insert_own" on public.attempts;
drop policy if exists "attempts_update_own" on public.attempts;
revoke insert,update on public.study_sessions from authenticated;
revoke insert,update on public.attempts from authenticated;

-- Seguridad por columna: un alumno no puede consultar claves con una petición directa.
revoke select on public.questions from authenticated;
grant select(id,external_id,bank_type,exam_type,bank_name,year,specialty,topic,subtopic,section,stem,options,
  source_reference,source_page,requires_image,image_url,status,source_uid,version,created_at,updated_at,archived_at,explanation_source)
on public.questions to authenticated;

create or replace function public.staff_list_questions(p_search text default '',p_status text default '',p_limit integer default 120,p_explanation_source text default '')
returns setof public.questions language plpgsql stable security definer set search_path=public as $$
begin
  if not public.is_staff() then raise exception 'No autorizado' using errcode='42501'; end if;
  return query select q.* from public.questions q
  where (coalesce(p_status,'')='' or q.status=p_status)
    and (coalesce(p_explanation_source,'')='' or q.explanation_source=p_explanation_source)
    and (coalesce(p_search,'')='' or q.external_id ilike '%'||p_search||'%' or q.stem ilike '%'||p_search||'%')
  order by q.updated_at desc limit least(greatest(coalesce(p_limit,120),1),500);
end; $$;
grant execute on function public.staff_list_questions(text,text,integer,text) to authenticated;

create or replace function public.staff_get_question(p_id uuid)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare q public.questions%rowtype;
begin
  if not public.is_staff() then raise exception 'No autorizado' using errcode='42501'; end if;
  select * into q from public.questions where id=p_id;
  return to_jsonb(q);
end; $$;
grant execute on function public.staff_get_question(uuid) to authenticated;

create or replace function public.admin_questions_by_external(p_ids text[])
returns setof public.questions language plpgsql stable security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'No autorizado' using errcode='42501'; end if;
  return query select q.* from public.questions q where q.external_id=any(p_ids);
end; $$;
grant execute on function public.admin_questions_by_external(text[]) to authenticated;

create or replace function public.user_attempt_history(p_limit integer default 1000)
returns table(question_id uuid,is_correct boolean,answered_at timestamptz,question jsonb)
language sql stable security definer set search_path=public as $$
  select a.question_id,a.is_correct,a.answered_at,
    (to_jsonb(q)-array['review_notes','source_hash','created_by','updated_by']) ||
    jsonb_build_object('explanation',case when q.explanation_source='AUTO_LOCAL' then '' else q.explanation end,
                       'galactic_tip',case when q.explanation_source='AUTO_LOCAL' then '' else q.galactic_tip end)
  from public.attempts a join public.study_sessions s on s.id=a.session_id left join public.questions q on q.id=a.question_id
  where a.user_id=auth.uid() and (s.status='COMPLETADA' or coalesce(s.filters->>'answer_mode','instant')='instant')
  order by a.answered_at desc limit least(greatest(coalesce(p_limit,1000),1),2000);
$$;
grant execute on function public.user_attempt_history(integer) to authenticated;

create or replace function public.user_progress_summary()
returns jsonb language sql stable security definer set search_path=public as $$
  select jsonb_build_object(
    'total',count(a.id),
    'correct',count(a.id) filter(where a.is_correct is true),
    'sessions',(select count(*) from public.study_sessions sx where sx.user_id=auth.uid() and sx.status='COMPLETADA')
  )
  from public.attempts a join public.study_sessions s on s.id=a.session_id
  where a.user_id=auth.uid() and (s.status='COMPLETADA' or coalesce(s.filters->>'answer_mode','instant')='instant');
$$;
grant execute on function public.user_progress_summary() to authenticated;

create or replace function public.user_topic_progress()
returns table(specialty text,topic text,total bigint,correct bigint,accuracy_pct numeric)
language sql stable security definer set search_path=public as $$
  select q.specialty,q.topic,count(*),count(*) filter(where a.is_correct is true),
    round(100.0*count(*) filter(where a.is_correct is true)/nullif(count(*),0),1)
  from public.attempts a join public.study_sessions s on s.id=a.session_id join public.questions q on q.id=a.question_id
  where a.user_id=auth.uid() and (s.status='COMPLETADA' or coalesce(s.filters->>'answer_mode','instant')='instant')
  group by q.specialty,q.topic order by 5 asc nulls last;
$$;
grant execute on function public.user_topic_progress() to authenticated;

-- Evita inferir la clave de un examen en curso consultando is_correct por REST.
revoke select on public.attempts from authenticated;
revoke select on public.v_user_topic_progress from authenticated;
revoke select on public.v_question_stats from authenticated;

create or replace function public.admin_list_users(p_search text default '')
returns table(id uuid,email text,full_name text,role text,plan text,target_exam text,created_at timestamptz)
language sql stable security definer set search_path=public,auth as $$
  select p.id,u.email,p.full_name,p.role,p.plan,p.target_exam,p.created_at
  from public.profiles p join auth.users u on u.id=p.id
  where public.is_admin() and (coalesce(p_search,'')='' or u.email ilike '%'||p_search||'%' or p.full_name ilike '%'||p_search||'%')
  order by p.created_at desc limit 200;
$$;
grant execute on function public.admin_list_users(text) to authenticated;

create or replace function public.admin_update_user(p_user uuid,p_role text,p_plan text)
returns void language plpgsql security definer set search_path=public as $$
declare admin_count integer;
begin
  if not public.is_admin() then raise exception 'No autorizado' using errcode='42501'; end if;
  if p_role not in ('student','moderator','admin') or p_plan not in ('free','pro','admin') then raise exception 'Valor inválido'; end if;
  if exists(select 1 from public.profiles where id=p_user and role='admin') and p_role<>'admin' then
    select count(*) into admin_count from public.profiles where role='admin';
    if admin_count<=1 then raise exception 'No puedes quitar el rol al último administrador'; end if;
  end if;
  update public.profiles set role=p_role,plan=p_plan where id=p_user;
end; $$;
grant execute on function public.admin_update_user(uuid,text,text) to authenticated;

-- v1.6.1: subrayados temporales por sesión y permisos de importación.
create or replace function public.reset_session_highlights()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if TG_OP='INSERT' then
    delete from public.user_highlights
    where user_id=new.user_id and question_id=any(new.question_ids);
  elsif old.status is distinct from new.status and new.status='COMPLETADA' then
    delete from public.user_highlights
    where user_id=new.user_id and question_id=any(new.question_ids);
  end if;
  return new;
end; $$;
drop trigger if exists reset_session_highlights_trigger on public.study_sessions;
create trigger reset_session_highlights_trigger
  after insert or update of status on public.study_sessions
  for each row execute function public.reset_session_highlights();

-- Reafirma los privilegios REST necesarios; RLS sigue limitando estas operaciones a admin.
grant select,insert,update,delete on public.import_batches,public.import_items to authenticated;
grant usage,select on sequence public.import_items_id_seq to authenticated;
grant insert,update,delete on public.questions to authenticated;
grant select,insert,update,delete on public.question_versions,public.simulation_sets,public.simulation_questions to authenticated;

drop policy if exists "imports_admin_all" on public.import_batches;
create policy "imports_admin_all" on public.import_batches for all to authenticated
using(public.is_admin()) with check(public.is_admin());
drop policy if exists "import_items_admin_all" on public.import_items;
create policy "import_items_admin_all" on public.import_items for all to authenticated
using(public.is_admin()) with check(public.is_admin());

create or replace function public.admin_import_preflight()
returns jsonb language sql stable security definer set search_path=public as $$
  select jsonb_build_object(
    'allowed',public.is_admin(),
    'role',coalesce((select role from public.profiles where id=auth.uid()),'sin perfil')
  );
$$;
grant execute on function public.admin_import_preflight() to authenticated;

commit;
