-- BANQO Perú · actualización v1.6 (correcciones de auditoría)
-- Ejecutar UNA VEZ en Supabase > SQL Editor para proyectos existentes.
-- Es aditiva: no borra preguntas, usuarios ni progreso.

begin;

-- Roles y metadatos editoriales.
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('student','moderator','admin'));

alter table public.questions add column if not exists explanation_source text not null default 'MANUAL';
alter table public.questions drop constraint if exists questions_explanation_source_check;
alter table public.questions add constraint questions_explanation_source_check
  check (explanation_source in ('MANUAL','AUTO_LOCAL','IA'));

alter table public.simulation_sets add column if not exists penalty numeric(6,3) not null default 0.333;

create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role in ('moderator','admin'));
$$;

-- Ajustes por usuario, sin números fijos repetidos en el cliente.
create table if not exists public.app_settings(
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);
insert into public.app_settings(key,value) values ('free_daily_questions','15'::jsonb)
on conflict (key) do nothing;
alter table public.app_settings enable row level security;
drop policy if exists "settings_read" on public.app_settings;
create policy "settings_read" on public.app_settings for select to authenticated using (true);
drop policy if exists "settings_admin_all" on public.app_settings;
create policy "settings_admin_all" on public.app_settings for all to authenticated
using (public.is_admin()) with check (public.is_admin());

create or replace function public.free_questions_remaining()
returns integer language plpgsql stable security definer set search_path=public as $$
declare uid uuid:=auth.uid(); p public.profiles%rowtype; used_n integer; daily_limit integer:=15;
begin
  if uid is null then raise exception 'No autenticado'; end if;
  select * into p from public.profiles where id=uid;
  if p.role in ('admin','moderator') or p.plan in ('pro','admin') then return -1; end if;
  select coalesce((value #>> '{}')::integer,15) into daily_limit
  from public.app_settings where key='free_daily_questions';
  select count(*)::integer into used_n from public.attempts
  where user_id=uid and selected_answer is not null
    and (answered_at at time zone 'America/Lima')::date=(now() at time zone 'America/Lima')::date;
  return greatest(0,coalesce(daily_limit,15)-used_n);
end; $$;

-- Resaltados guardados como offsets de texto, nunca como HTML.
create table if not exists public.user_highlights(
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  start_offset integer not null check(start_offset>=0),
  end_offset integer not null check(end_offset>start_offset),
  color text not null default 'yellow' check(color in ('yellow','green','blue','pink')),
  created_at timestamptz not null default now(),
  unique(user_id,question_id,start_offset,end_offset)
);
alter table public.user_highlights enable row level security;
drop policy if exists "highlights_own" on public.user_highlights;
create policy "highlights_own" on public.user_highlights for all to authenticated
using(user_id=auth.uid()) with check(user_id=auth.uid());

-- Estado de pregunta no contestada (marcada/descartes) sin consumir cupo Free.
create table if not exists public.study_question_state(
  session_id uuid not null references public.study_sessions(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  marked boolean not null default false,
  discarded_options text[] not null default '{}'::text[],
  updated_at timestamptz not null default now(),
  primary key(session_id,question_id)
);
alter table public.study_question_state enable row level security;
drop policy if exists "study_question_state_own" on public.study_question_state;
create policy "study_question_state_own" on public.study_question_state for all to authenticated
using(user_id=auth.uid()) with check(user_id=auth.uid());

-- Perfil: el alumno puede editar datos propios sin elevar rol, plan, XP o racha.
create or replace function public.protect_profile_privileges()
returns trigger language plpgsql set search_path=public as $$
begin
  if old.role='admin' and new.role<>'admin' and (select count(*) from public.profiles where role='admin')<=1 then
    raise exception 'No puedes quitar el rol al último administrador';
  end if;
  if auth.uid()=old.id and not public.is_admin() then
    new.role:=old.role; new.plan:=old.plan; new.xp:=old.xp; new.streak:=old.streak;
  end if;
  return new;
end; $$;
drop trigger if exists protect_profile_privileges_trigger on public.profiles;
create trigger protect_profile_privileges_trigger before update on public.profiles
for each row execute function public.protect_profile_privileges();
drop policy if exists "profiles_update_own_safe" on public.profiles;
create policy "profiles_update_own_safe" on public.profiles for update to authenticated
using(id=auth.uid()) with check(id=auth.uid());

-- Staff puede revisar; sólo admin importa, elimina y publica.
drop policy if exists "questions_read_published" on public.questions;
create policy "questions_read_published" on public.questions for select to authenticated
using(status='PUBLICADA' or public.is_staff());
drop policy if exists "questions_staff_update" on public.questions;
create policy "questions_staff_update" on public.questions for update to authenticated
using(public.is_staff()) with check(public.is_staff());
drop policy if exists "question_versions_admin_all" on public.question_versions;
create policy "question_versions_staff_all" on public.question_versions for all to authenticated
using(public.is_staff()) with check(public.is_staff());
drop policy if exists "simsets_read_published" on public.simulation_sets;
create policy "simsets_read_published_or_staff" on public.simulation_sets for select to authenticated
using(status='PUBLICADO' or public.is_staff());
drop policy if exists "simq_read_published" on public.simulation_questions;
create policy "simq_read_published_or_staff" on public.simulation_questions for select to authenticated
using(public.is_staff() or exists(select 1 from public.simulation_sets s where s.id=simulation_id and s.status='PUBLICADO'));
drop policy if exists "reports_select_own_or_admin" on public.question_reports;
create policy "reports_select_own_or_staff" on public.question_reports for select to authenticated
using(user_id=auth.uid() or public.is_staff());
drop policy if exists "reports_admin_update" on public.question_reports;
create policy "reports_staff_update" on public.question_reports for update to authenticated
using(public.is_staff()) with check(public.is_staff());

create or replace function public.protect_question_publication()
returns trigger language plpgsql set search_path=public as $$
begin
  if old.status is distinct from new.status and (old.status='PUBLICADA' or new.status='PUBLICADA') and not public.is_admin() then
    raise exception 'Sólo un administrador puede publicar o retirar preguntas' using errcode='42501';
  end if;
  return new;
end; $$;
drop trigger if exists protect_question_publication_trigger on public.questions;
create trigger protect_question_publication_trigger before update on public.questions
for each row execute function public.protect_question_publication();

-- El moderador puede corregir y adjuntar recursos, pero no eliminar archivos.
drop policy if exists "question_assets_admin_write" on storage.objects;
drop policy if exists "question_assets_admin_update" on storage.objects;
drop policy if exists "question_assets_staff_write" on storage.objects;
drop policy if exists "question_assets_staff_update" on storage.objects;
create policy "question_assets_staff_write" on storage.objects for insert to authenticated
with check(bucket_id='question-assets' and public.is_staff());
create policy "question_assets_staff_update" on storage.objects for update to authenticated
using(bucket_id='question-assets' and public.is_staff()) with check(bucket_id='question-assets' and public.is_staff());

-- Una simulación sólo puede publicarse si todas sus preguntas activas están publicadas.
create or replace function public.simulation_readiness(p_sim uuid)
returns jsonb language sql stable security definer set search_path=public as $$
  select jsonb_build_object(
    'total',count(*) filter(where not sq.is_reserve),
    'published',count(*) filter(where not sq.is_reserve and q.status='PUBLICADA'),
    'pending',count(*) filter(where not sq.is_reserve and q.status<>'PUBLICADA')
  ) from public.simulation_questions sq join public.questions q on q.id=sq.question_id
  where sq.simulation_id=p_sim;
$$;
grant execute on function public.simulation_readiness(uuid) to authenticated;

create or replace function public.publish_simulation_questions(p_sim uuid)
returns integer language plpgsql security definer set search_path=public as $$
declare n integer;
begin
  if not public.is_admin() then raise exception 'No autorizado' using errcode='42501'; end if;
  update public.questions q set status='PUBLICADA',updated_by=auth.uid()
  from public.simulation_questions sq
  where sq.simulation_id=p_sim and sq.question_id=q.id and not sq.is_reserve
    and q.status in ('PENDIENTE','APROBADA');
  get diagnostics n=row_count; return n;
end; $$;
grant execute on function public.publish_simulation_questions(uuid) to authenticated;

-- JSON seguro: mientras una sesión está en curso, nunca entrega clave/explicación.
create or replace function public.safe_question(q public.questions)
returns jsonb language sql immutable as $$
  select to_jsonb(q)-array['correct_answer','explanation','galactic_tip','review_notes','created_by','updated_by','source_hash'];
$$;

create or replace function public.start_practice(
  p_count integer, p_mode text, p_filters jsonb default '{}'::jsonb, p_random boolean default true,
  p_question_ids uuid[] default null
) returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); ids uuid[]; sid uuid; qs jsonb; allowed integer; requested integer;
begin
  if uid is null then raise exception 'No autenticado'; end if;
  requested:=greatest(1,least(coalesce(p_count,15),100)); allowed:=public.free_questions_remaining();
  if allowed=0 then raise exception 'FREE_LIMIT_REACHED' using errcode='P0001'; end if;
  if allowed>=0 then requested:=least(requested,allowed); end if;
  if p_mode not in ('instant','exam') then p_mode:='instant'; end if;

  if p_question_ids is not null then
    select array_agg(x.id order by array_position(p_question_ids,x.id)) into ids from (
      select id from public.questions where id=any(p_question_ids) and status='PUBLICADA'
      order by array_position(p_question_ids,id) limit requested
    ) x;
  elsif p_random then
    select array_agg(id) into ids from (
      select id from public.questions q where q.status='PUBLICADA'
      and (coalesce(p_filters->>'exam','')='' or q.exam_type=p_filters->>'exam')
      and (coalesce(p_filters->>'bank','')='' or q.bank_name=p_filters->>'bank')
      and (coalesce(p_filters->>'specialty','')='' or q.specialty=p_filters->>'specialty')
      and (coalesce(p_filters->>'topic','')='' or q.topic=p_filters->>'topic')
      and (coalesce(p_filters->>'subtopic','')='' or q.subtopic=p_filters->>'subtopic')
      order by random() limit requested
    ) x;
  else
    select array_agg(id) into ids from (
      select id from public.questions q where q.status='PUBLICADA'
      and (coalesce(p_filters->>'exam','')='' or q.exam_type=p_filters->>'exam')
      and (coalesce(p_filters->>'bank','')='' or q.bank_name=p_filters->>'bank')
      and (coalesce(p_filters->>'specialty','')='' or q.specialty=p_filters->>'specialty')
      and (coalesce(p_filters->>'topic','')='' or q.topic=p_filters->>'topic')
      and (coalesce(p_filters->>'subtopic','')='' or q.subtopic=p_filters->>'subtopic')
      order by q.external_id limit requested
    ) x;
  end if;
  if coalesce(array_length(ids,1),0)=0 then raise exception 'NO_QUESTIONS' using errcode='P0001'; end if;
  insert into public.study_sessions(user_id,session_type,filters,question_ids)
  values(uid,'PRACTICE',coalesce(p_filters,'{}'::jsonb)||jsonb_build_object('answer_mode',p_mode),ids)
  returning id into sid;
  select jsonb_agg(public.safe_question(q) order by array_position(ids,q.id)) into qs
  from public.questions q where q.id=any(ids);
  return jsonb_build_object('session_id',sid,'questions',coalesce(qs,'[]'::jsonb),'allowed',allowed);
end; $$;
grant execute on function public.start_practice(integer,text,jsonb,boolean,uuid[]) to authenticated;

create or replace function public.start_simulation(p_sim uuid,p_mode text default 'exam')
returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); sim public.simulation_sets%rowtype; ids uuid[]; sid uuid; qs jsonb; allowed integer;
begin
  if uid is null then raise exception 'No autenticado'; end if;
  select * into sim from public.simulation_sets where id=p_sim and status='PUBLICADO';
  if sim.id is null then raise exception 'SIMULATION_NOT_AVAILABLE' using errcode='P0001'; end if;
  select array_agg(sq.question_id order by sq.order_no) into ids
  from public.simulation_questions sq join public.questions q on q.id=sq.question_id
  where sq.simulation_id=p_sim and not sq.is_reserve and q.status='PUBLICADA';
  if coalesce(array_length(ids,1),0)<>sim.question_count then raise exception 'SIMULATION_NOT_READY' using errcode='P0001'; end if;
  allowed:=public.free_questions_remaining();
  if allowed>=0 and allowed<array_length(ids,1) then raise exception 'FREE_SIMULATION_LIMIT' using errcode='P0001'; end if;
  if p_mode not in ('instant','exam') then p_mode:='exam'; end if;
  insert into public.study_sessions(user_id,session_type,simulation_id,filters,question_ids)
  values(uid,'SIMULATION',sim.id,jsonb_build_object('name',sim.name,'answer_mode',p_mode),ids) returning id into sid;
  select jsonb_agg(public.safe_question(q) order by array_position(ids,q.id)) into qs
  from public.questions q where q.id=any(ids);
  return jsonb_build_object('session_id',sid,'simulation',to_jsonb(sim),'questions',qs);
end; $$;
grant execute on function public.start_simulation(uuid,text) to authenticated;

create or replace function public.resume_study_session(p_session uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); s public.study_sessions%rowtype; qs jsonb; ans jsonb; st jsonb;
begin
  select * into s from public.study_sessions where id=p_session and user_id=uid;
  if s.id is null then raise exception 'Sesión no encontrada'; end if;
  if s.status='COMPLETADA' then
    select jsonb_agg(((to_jsonb(q)-array['review_notes','source_hash','created_by','updated_by'])||jsonb_build_object('explanation',case when q.explanation_source='AUTO_LOCAL' then '' else q.explanation end,'galactic_tip',case when q.explanation_source='AUTO_LOCAL' then '' else q.galactic_tip end)) order by array_position(s.question_ids,q.id)) into qs from public.questions q where q.id=any(s.question_ids);
  else
    select jsonb_agg(public.safe_question(q) order by array_position(s.question_ids,q.id)) into qs from public.questions q where q.id=any(s.question_ids);
  end if;
  select coalesce(jsonb_object_agg(question_id::text,selected_answer) filter(where selected_answer is not null),'{}'::jsonb) into ans
  from public.attempts where session_id=s.id and user_id=uid;
  select coalesce(jsonb_object_agg(question_id::text,jsonb_build_object('marked',marked,'discarded',discarded_options)),'{}'::jsonb) into st
  from public.study_question_state where session_id=s.id and user_id=uid;
  return jsonb_build_object('session',to_jsonb(s),'questions',coalesce(qs,'[]'::jsonb),'answers',ans,'question_state',st);
end; $$;
grant execute on function public.resume_study_session(uuid) to authenticated;

create or replace function public.save_question_state(p_session uuid,p_question uuid,p_marked boolean,p_discarded text[])
returns void language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid();
begin
  if not exists(select 1 from public.study_sessions where id=p_session and user_id=uid and status='EN_CURSO' and p_question=any(question_ids))
    then raise exception 'Sesión no válida' using errcode='42501'; end if;
  insert into public.study_question_state(session_id,user_id,question_id,marked,discarded_options)
  values(p_session,uid,p_question,coalesce(p_marked,false),coalesce(p_discarded,'{}'::text[]))
  on conflict(session_id,question_id) do update set marked=excluded.marked,discarded_options=excluded.discarded_options,updated_at=now();
end; $$;
grant execute on function public.save_question_state(uuid,uuid,boolean,text[]) to authenticated;

create or replace function public.answer_question(
  p_session uuid,p_question uuid,p_letter text,p_marked boolean default false,
  p_discarded text[] default '{}'::text[],p_response_ms integer default null
) returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); s public.study_sessions%rowtype; q public.questions%rowtype; ok boolean; mode text; remaining integer;
begin
  if uid is null then raise exception 'No autenticado'; end if;
  perform pg_advisory_xact_lock(hashtext(uid::text));
  select * into s from public.study_sessions where id=p_session and user_id=uid and status='EN_CURSO' for update;
  if s.id is null or not p_question=any(s.question_ids) then raise exception 'Sesión no válida' using errcode='42501'; end if;
  if upper(p_letter) not in ('A','B','C','D','E') then raise exception 'Respuesta no válida'; end if;
  if not exists(select 1 from public.attempts where session_id=p_session and question_id=p_question and selected_answer is not null) then
    remaining:=public.free_questions_remaining();
    if remaining=0 then raise exception 'FREE_LIMIT_REACHED' using errcode='P0001'; end if;
  end if;
  select * into q from public.questions where id=p_question;
  ok:=upper(p_letter)=q.correct_answer; mode:=coalesce(s.filters->>'answer_mode','instant');
  insert into public.attempts(session_id,user_id,question_id,selected_answer,is_correct,marked,discarded_options,response_ms,answered_at)
  values(p_session,uid,p_question,upper(p_letter),ok,coalesce(p_marked,false),coalesce(p_discarded,'{}'::text[]),greatest(0,p_response_ms),now())
  on conflict(session_id,question_id) do update set selected_answer=excluded.selected_answer,is_correct=excluded.is_correct,
    marked=excluded.marked,discarded_options=excluded.discarded_options,response_ms=excluded.response_ms,answered_at=now();
  perform public.save_question_state(p_session,p_question,p_marked,p_discarded);
  if mode='instant' then
    return jsonb_build_object('ok',true,'is_correct',ok,'correct_answer',q.correct_answer,
      'explanation',case when q.explanation_source='AUTO_LOCAL' then '' else q.explanation end,
      'galactic_tip',case when q.explanation_source='AUTO_LOCAL' then '' else q.galactic_tip end);
  end if;
  return jsonb_build_object('ok',true);
end; $$;
grant execute on function public.answer_question(uuid,uuid,text,boolean,text[],integer) to authenticated;

create or replace function public.complete_study_session(p_session uuid,p_elapsed integer default 0)
returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); s public.study_sessions%rowtype; total integer; correct_n integer; incorrect_n integer; blank_n integer; score_n numeric; qs jsonb;
begin
  select * into s from public.study_sessions where id=p_session and user_id=uid for update;
  if s.id is null then raise exception 'Sesión no encontrada' using errcode='42501'; end if;
  total:=coalesce(array_length(s.question_ids,1),0);
  select count(*) filter(where is_correct is true),count(*) filter(where selected_answer is not null and is_correct is false)
    into correct_n,incorrect_n from public.attempts where session_id=s.id and user_id=uid;
  blank_n:=greatest(0,total-correct_n-incorrect_n); score_n:=case when total=0 then 0 else round(correct_n*100.0/total,2) end;
  update public.study_sessions set status='COMPLETADA',correct_count=correct_n,incorrect_count=incorrect_n,
    blank_count=blank_n,score=score_n,elapsed_seconds=greatest(0,p_elapsed),finished_at=coalesce(finished_at,now()) where id=s.id;
  select jsonb_agg(((to_jsonb(q)-array['review_notes','source_hash','created_by','updated_by'])||jsonb_build_object('explanation',case when q.explanation_source='AUTO_LOCAL' then '' else q.explanation end,
    'galactic_tip',case when q.explanation_source='AUTO_LOCAL' then '' else q.galactic_tip end)) order by array_position(s.question_ids,q.id))
    into qs from public.questions q where q.id=any(s.question_ids);
  return jsonb_build_object('correct',correct_n,'incorrect',incorrect_n,'blank',blank_n,'score',score_n,'questions',coalesce(qs,'[]'::jsonb));
end; $$;
grant execute on function public.complete_study_session(uuid,integer) to authenticated;

-- Taxonomía y progreso sin descargar miles de filas completas.
create or replace view public.v_active_taxonomy with(security_invoker=true) as
select exam_type,bank_name,specialty,topic,subtopic,count(*)::integer available
from public.questions where status='PUBLICADA' group by 1,2,3,4,5;

create or replace view public.v_user_topic_progress with(security_invoker=true) as
select a.user_id,q.specialty,q.topic,count(*)::integer total,
  count(*) filter(where a.is_correct is true)::integer correct,
  round(100.0*count(*) filter(where a.is_correct is true)/nullif(count(*),0),1) accuracy_pct
from public.attempts a join public.questions q on q.id=a.question_id
group by a.user_id,q.specialty,q.topic;
grant select on public.v_active_taxonomy,public.v_user_topic_progress to authenticated;

-- Administración de usuarios sin exponer auth.users a estudiantes.

-- Sesiones y respuestas sólo se escriben mediante RPC validadas en servidor.
drop policy if exists "sessions_insert_own" on public.study_sessions;
drop policy if exists "sessions_update_own" on public.study_sessions;
drop policy if exists "attempts_insert_own" on public.attempts;
drop policy if exists "attempts_update_own" on public.attempts;
revoke insert,update on public.study_sessions from authenticated;
revoke insert,update on public.attempts from authenticated;

-- Seguridad por columna: un alumno no puede consultar claves con una petición directa.
revoke select on public.questions from authenticated;
grant select(id,external_id,bank_type,exam_type,bank_name,year,specialty,topic,subtopic,section,stem,options,
  source_reference,source_page,requires_image,image_url,status,source_uid,version,created_at,updated_at,archived_at,explanation_source)
on public.questions to authenticated;

create or replace function public.staff_list_questions(p_search text default '',p_status text default '',p_limit integer default 120,p_explanation_source text default '')
returns setof public.questions language plpgsql stable security definer set search_path=public as $$
begin
  if not public.is_staff() then raise exception 'No autorizado' using errcode='42501'; end if;
  return query select q.* from public.questions q
  where (coalesce(p_status,'')='' or q.status=p_status)
    and (coalesce(p_explanation_source,'')='' or q.explanation_source=p_explanation_source)
    and (coalesce(p_search,'')='' or q.external_id ilike '%'||p_search||'%' or q.stem ilike '%'||p_search||'%')
  order by q.updated_at desc limit least(greatest(coalesce(p_limit,120),1),500);
end; $$;
grant execute on function public.staff_list_questions(text,text,integer,text) to authenticated;

create or replace function public.staff_get_question(p_id uuid)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare q public.questions%rowtype;
begin
  if not public.is_staff() then raise exception 'No autorizado' using errcode='42501'; end if;
  select * into q from public.questions where id=p_id;
  return to_jsonb(q);
end; $$;
grant execute on function public.staff_get_question(uuid) to authenticated;

create or replace function public.admin_questions_by_external(p_ids text[])
returns setof public.questions language plpgsql stable security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'No autorizado' using errcode='42501'; end if;
  return query select q.* from public.questions q where q.external_id=any(p_ids);
end; $$;
grant execute on function public.admin_questions_by_external(text[]) to authenticated;

create or replace function public.user_attempt_history(p_limit integer default 1000)
returns table(question_id uuid,is_correct boolean,answered_at timestamptz,question jsonb)
language sql stable security definer set search_path=public as $$
  select a.question_id,a.is_correct,a.answered_at,
    (to_jsonb(q)-array['review_notes','source_hash','created_by','updated_by']) ||
    jsonb_build_object('explanation',case when q.explanation_source='AUTO_LOCAL' then '' else q.explanation end,
                       'galactic_tip',case when q.explanation_source='AUTO_LOCAL' then '' else q.galactic_tip end)
  from public.attempts a join public.study_sessions s on s.id=a.session_id left join public.questions q on q.id=a.question_id
  where a.user_id=auth.uid() and (s.status='COMPLETADA' or coalesce(s.filters->>'answer_mode','instant')='instant')
  order by a.answered_at desc limit least(greatest(coalesce(p_limit,1000),1),2000);
$$;
grant execute on function public.user_attempt_history(integer) to authenticated;

create or replace function public.user_progress_summary()
returns jsonb language sql stable security definer set search_path=public as $$
  select jsonb_build_object(
    'total',count(a.id),
    'correct',count(a.id) filter(where a.is_correct is true),
    'sessions',(select count(*) from public.study_sessions sx where sx.user_id=auth.uid() and sx.status='COMPLETADA')
  )
  from public.attempts a join public.study_sessions s on s.id=a.session_id
  where a.user_id=auth.uid() and (s.status='COMPLETADA' or coalesce(s.filters->>'answer_mode','instant')='instant');
$$;
grant execute on function public.user_progress_summary() to authenticated;

create or replace function public.user_topic_progress()
returns table(specialty text,topic text,total bigint,correct bigint,accuracy_pct numeric)
language sql stable security definer set search_path=public as $$
  select q.specialty,q.topic,count(*),count(*) filter(where a.is_correct is true),
    round(100.0*count(*) filter(where a.is_correct is true)/nullif(count(*),0),1)
  from public.attempts a join public.study_sessions s on s.id=a.session_id join public.questions q on q.id=a.question_id
  where a.user_id=auth.uid() and (s.status='COMPLETADA' or coalesce(s.filters->>'answer_mode','instant')='instant')
  group by q.specialty,q.topic order by 5 asc nulls last;
$$;
grant execute on function public.user_topic_progress() to authenticated;

-- Evita inferir la clave de un examen en curso consultando is_correct por REST.
revoke select on public.attempts from authenticated;
revoke select on public.v_user_topic_progress from authenticated;
revoke select on public.v_question_stats from authenticated;

create or replace function public.admin_list_users(p_search text default '')
returns table(id uuid,email text,full_name text,role text,plan text,target_exam text,created_at timestamptz)
language sql stable security definer set search_path=public,auth as $$
  select p.id,u.email,p.full_name,p.role,p.plan,p.target_exam,p.created_at
  from public.profiles p join auth.users u on u.id=p.id
  where public.is_admin() and (coalesce(p_search,'')='' or u.email ilike '%'||p_search||'%' or p.full_name ilike '%'||p_search||'%')
  order by p.created_at desc limit 200;
$$;
grant execute on function public.admin_list_users(text) to authenticated;

create or replace function public.admin_update_user(p_user uuid,p_role text,p_plan text)
returns void language plpgsql security definer set search_path=public as $$
declare admin_count integer;
begin
  if not public.is_admin() then raise exception 'No autorizado' using errcode='42501'; end if;
  if p_role not in ('student','moderator','admin') or p_plan not in ('free','pro','admin') then raise exception 'Valor inválido'; end if;
  if exists(select 1 from public.profiles where id=p_user and role='admin') and p_role<>'admin' then
    select count(*) into admin_count from public.profiles where role='admin';
    if admin_count<=1 then raise exception 'No puedes quitar el rol al último administrador'; end if;
  end if;
  update public.profiles set role=p_role,plan=p_plan where id=p_user;
end; $$;
grant execute on function public.admin_update_user(uuid,text,text) to authenticated;

commit;
